theforeman/smart_proxy_openscap

lib/smart_proxy_openscap/openscap_api.rb
We have refactored develop proxy and extracted the SSL client cert handling
code. Please review. This is needed only if this plugin uses SSL client
certification verification. If not, please close it.
=> Added authorize_with_ssl_client

lib/smart_proxy_openscap/openscap_lib.rb
Smart Proxy 1.8+ introduces [```Proxy::FileLock```](https://github.com/theforeman/smart-proxy/blob/develop/lib/proxy/file_lock.rb) module
=> align file locking / unlocking methods to latest smart-proxy

lib/smart_proxy_openscap/openscap_lib.rb
If foreman runs on sub-uri (e.g. example.com/foreman) which is set as foreman_url in smart proxy, the sub-uri part gets dropped because we specify the path as absolute. For more details why we shouldn't put slash in the beginning, see http://projects.theforeman.org/issues/9740 (and related PR).
=> Fixes the URL for sub-uri deployments

bin/smart-proxy-openscap-send
Add the full path, or ```smart-proxy-openscap-send``` will fail to find the log location
=> fixes #10686 - Add path to smart proxy for openscap-send log

lib/smart_proxy_openscap/openscap_api.rb, lib/smart_proxy_openscap/storage.rb, lib/smart_proxy_openscap/storage_fs.rb, test/get_report_xml_html_test.rb
Deleting the Arf report files - proxy side of things
=> Fixes #12390 - Arf reports get deleted from Smart Proxy

README.md
Should be surrounded by '', otherwise:
```
Gemfile syntax error (eval):2: syntax error, unexpected tLABEL
...proxy_openscap', :git => https://github.com/theforeman/smart...
...                               ^
(eval):2: unknown regexp options - gthb
```
=> fixes #15125 - incorrect syntax in example

lib/smart_proxy_openscap/storage_fs.rb
Ruby 1.8.7 does not have `.size` instance method, only class method (which is kept on later versions)
=> Fixes #15388 - Use File.size class method instead of instance method

lib/smart_proxy_openscap/fetch_file.rb, lib/smart_proxy_openscap/fetch_scap_content.rb, lib/smart_proxy_openscap/fetch_tailoring_file.rb, lib/smart_proxy_openscap/openscap_api.rb, lib/smart_proxy_openscap/openscap_content_parser.rb, lib/smart_proxy_openscap/openscap_lib.rb, lib/smart_proxy_openscap/openscap_plugin.rb, settings.d/openscap.yml.example, smart_proxy_openscap.gemspec, test/data/tailoring.xml, test/fetch_tailoring_api_test.rb, test/scap_content_parser_api_test.rb
Will need [this](https://github.com/OpenSCAP/ruby-openscap/pull/9) to work.
=> Fixes #14158 - Add tailoring file for scans

bin/smart-proxy-openscap-send
:laughing: 
BTW, does anyone know why line 42 has `puts ` and not `logger`?
=> Fixes #18086 - Fix typo in smart-proxy-openscap-send

lib/smart_proxy_openscap/foreman_forwarder.rb, lib/smart_proxy_openscap/openscap_api.rb, lib/smart_proxy_openscap/openscap_content_parser.rb, lib/smart_proxy_openscap/openscap_report_parser.rb
I found out that devel proxy will increase memory usage even if you make request to /features many times. I generated and parsed 10000 reports in production with this and memory usage for proxy changed from 0.0% to 0.1%, so it seems to take care of the issue.
=> Fixes #18926 - Destroy openscap objects to release memory

lib/smart_proxy_openscap/spool_forwarder.rb
smart_proxy_openscap doesn't officially say what version of proxy is required AFAICT, and multi-line statements on 1.8.7 require the . to be on the first line.
=> fixes #19196 - fix ruby 1.8.7 incompatability

bin/smart-proxy-parse-arf, lib/smart_proxy_openscap/arf_parser.rb, lib/smart_proxy_openscap/foreman_forwarder.rb, lib/smart_proxy_openscap/openscap_report_parser.rb
TODO:
`shell_command` and `popen` methods are not available in 6.2, so we have to add them when cherry picking for downstream.
=> Fixes #20164 - Use a separate script to parse reports

lib/smart_proxy_openscap/arf_html.rb, lib/smart_proxy_openscap/policy_guide.rb, lib/smart_proxy_openscap/scap_profiles.rb, lib/smart_proxy_openscap/scap_validation.rb
I have no proofs this fixes any memory leaks at all, but it is a good practice to add those ensure blocks. I have a suspicion that it might help my customer to mitigate memory leaks in Satellite 6.2 branch.
=> Fixes #21164 - add missing ensure blocks

bin/smart-proxy-openscap-send, lib/smart_proxy_openscap/openscap_lib.rb, lib/smart_proxy_openscap/spool_forwarder.rb
Simply calling `settings` on our plugin does not work any more, we need to initialize plugins to get the settings loaded. Unfortunately, we get the initializing info printed to the logs:
@witlessbird, is there a better way to do this?
=> Fixes #22511 - Load settings when sending from spool

bin/smart-proxy-openscap-send
On CentOS/RHEL 8 Foreman and the Smart Proxy does not run using SCL so the command `smart-proxy-openscap-send` fails. This is an easy fix by checking for the command `scl` which could perhaps be improved.
=> fixes #30576 - Do not use scl if not avaiable

lib/smart_proxy_openscap/openscap_api.rb
This has been deprecated for ages, I think we should remove it at some point.
=> Fixes #17935 - Remove endpoint for scap_content download

lib/smart_proxy_openscap/openscap_api.rb
An improper authorization handling flaw was found in Foreman. The OpenSCAP plugin for the smart-proxy allows foreman clients to execute actions that should be limited to the Foreman Server. This flaw allows an authenticated local attacker to access and delete limited resources and also causes a denial of service on the Foreman server. The highest threat from this vulnerability is to integrity and system availability.
https://access.redhat.com/security/cve/CVE-2021-20290
=> Fixes #32257 - use trusted hosts to authorize clients

lib/smart_proxy_openscap/content_parser.rb
During the transition to the openscap_parser gem to avoid using the
ffi wrappers around the C library, a trivial validation was introduced.
Such validation turned to be very limited and not supporting non-RH
valid SCAP content. This patch removes the validation. The only proper
solution would be to shell out to the oscap tool, but the purpose was to
be independent of it.
=> Fixes #34554 - remove the improper validation

lib/smart_proxy_openscap/helpers.rb, lib/smart_proxy_openscap/openscap_api.rb
Parsing of report XMLs seems to be the biggest thing that makes memory consupmtion skyrocket. This change attempts to mitigate that by forking off a child process, inside which the parsing happens. Once the parsing is done, the child process exits and the additional memory it accumulated gets released. The parsed report is sent back to the parent process through a pipe.
The error handling is slightly iffy here, if the child exits with non-zero exit code, we assume that an exception was raised in it and either try to reconstruct the original exception from the data we get from the child or just raise a general exception.
When foreman-proxy starts it seems to take ~70MB. I then proceeded to upload five reports and checked the memory consupmtion again. Without this patch, it went to ~1.3GB, …
=> Fixes #37554 - Fork before parsing report XML

Gemfile
Bundler 2.3 has learned to deal with git repos that name their branch something other than develop, but only Ruby 3.1 started to ship that version.
Fixes: cab14f214676 ("Respect SMART_PROXY_BRANCH for better CI support")
=> Support bundler < 2.3 again
